--- # Adding users
- hosts: 10.95.1.93
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Creating users in nodes
    user:
     name: "{{item.name}}"
     groups: "{{ item.groups }}"
     state: present
     comment: "{{item.comment}}"
     shell: /bin/bash
     home: /home/{{item.name}}
    with_items:
     - { name: 'prasansa', groups: 'root', comment: 'Sai Prasanna'}
    register: result
  - debug: var=result
     
#   ~playbooks/users/users.yml 
#   ssh_users:
#    - name: user1
#      key: "{{ lookup('file', '/home/ec2-user/files/user1.pub') }}"
#    - name: user2
#      key: "{{ lookup('file', '/home/ec2-user/files/user2.pub') }}"
#    - name: user3
#      key: "{{ lookup('file', '/home/ec2-user/files/user3.pub') }}"
#    - name: user4
#      key: "{{ lookup('file', '/home/ec2-user/files/user4.pub') }}"

# - include: ~playbooks/users/users.yml
 
  - name: Adding authorized key to the user "{{item.name}}"
    authorized_key:
     user: "{{item.name}}"
     state: present                               
     key: "{{lookup('file','/home/ec2-user/files/authorized_keys.users.pub')}}" 
     #    "{{lookup('file', '"{{item.key}}"'}}"
    with_items: #ssh_users
     - { name: 'prasansa'}
    register: result
  - debug: var=result    
