--- # Adding users
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Copying file from s3 to files
    shell: aws s3 cp s3://syn-devops/public_keys/*.pub /home/ec2-user/files/

- hosts: all
# - hosts: tag_Name_Value
  remote_user: ec2-user
  become: yes
  vars_files: 
  - users/user.yml
  tasks:
  - name: Creating users in nodes
    user:
     name: "{{item.name}}"
     groups: "{{ item.groups }}"
     comment: "{{item.comment}}"
     shell: /bin/bash
     home: /home/{{item.name}}
     state: present
    with_items:
     - "{{ssh_users}}"
     
#   ~playbooks/users/user.yml
#   ssh_users:
#    - name: user1
#      key: "{{ lookup('file', '/home/ec2-user/files/user1.pub') }}"
#    - name: user2
#      key: "{{ lookup('file', '/home/ec2-user/files/user2.pub') }}"
#    - name: user3
#      key: "{{ lookup('file', '/home/ec2-user/files/user3.pub') }}"
#    - name: user4
#      key: "{{ lookup('file', '/home/ec2-user/files/user4.pub') }}"

  - name: Adding authorized key to the user "{{item.name}}"
    authorized_key:
     user: "{{item.name}}"
     state: present    
     key: "{{item.key}}"
     # "{{lookup('file','/home/ec2-user/files/authorized_keys.users.pub')}}" 
    with_items:
     - "{{ssh_users}}"
    # - { name: 'prasansa'}
    register: result
  - debug: var=result    