--- # FULL INCLUDE TASKS example
- hosts: webhosts
  sudo: yes
  connection: ssh
  gather_facts: no 
  tasks: 
    - include: plays/packages.yml
    - name:  Verify the telnet package
      raw: yum list installed | grep telnet > /home/test/pkgs.log
      register: result
    - debug: var=result 
