--- # FULL INCLUDE TASKS example
- hosts: webhosts
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no 
  tasks: 
    - include: plays/packages.yml 
    - name:  Verify the telnet package
      raw: yum list installed | grep telnet > /home/test/pkgs.log
     
