--- # CHECK DISK SPACE
- hosts: tag_monitor_disk_space_true
  remote_user: ec2-user
  become: yes
  connection: ssh
  gather_facts: True
  vars:
      diskPercentage: 0.5
      Percentage: 50%
      days: 7
  tasks:
    - name: Test for Available Disk Space
      assert:
        that:
         - "item.mount == '/' and ( item.size_available > ( item.size_total|float * {{diskPercentage}} ) )"
#         - not {{ item.mount == '/var' and ( item.size_available < item.size_total - ( item.size_total|float * 0.0) ) }}
      with_items: "{{ ansible_mounts }}"
      ignore_errors: yes
      register: disk_free
#   - name: Fail when disk space needs attention
#      fail:
#        msg: 'Disk space needs attention.'
#     when: disk_free|failed
    - name: Cleaning the Disk Space
      #command: find /home/apache22/logs/ -name "*log*"  -mtime +7 -exec rm {} \;
      command: find /home/apache22/logs/ -name "*log*"  -mtime +{{days}} -exec ls  {} \;
#      when: disk_free|failed
      notify:  Alert Slack
      when: disk_free|failed
      register: result
    - debug: var=result
  handlers:
    - name: Alerting Slack before Clean Up
      slack:
        token: T029A195J/B5XRN9535/XgoMGAfaGgPyF4UKXHF2L4pZ
        channel: #syn-newrelic
        msg: "Disk Space for {{inventory_hostname}} host is less than {{Percentage}}, so cleaning it up... "
      listen: Alert Slack
    - name: Alerting Slack after Clean Up
      slack:
        token: T029A195J/B5XRN9535/XgoMGAfaGgPyF4UKXHF2L4pZ
        channel: #syn-newrelic
        msg: "DiskSpace for {{inventory_hostname}} host which went less than {{Percentage}} of total disk space has been cleaned."
      listen: Alert Slack
      delegate_to: localhost