--- # Discrete Plays
- hosts: webhosts
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no 
  tasks:  
    - include: plays/packages.yml
    - name: Verifying the package is installed or not
      raw: yum list installed | grep telnet  >> /home/test/pkgs.log
