--- # LookUp PlayBook Example
- hosts: webhosts
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
     - debug: msg= " {{lookup('env','HOME')}} is the value listed"

   # - debug: msg="Lookup the Super Hero for BRUCE WAYNE {{ lookup('csvfile', 'Bruce Wayne file = lookup.csv delimiter=, default=NOMATCH')}}"
      
