--- # PROMPT-2 Example Playbook
- hosts: webhosts
  sudo: yes
  user: test
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.01b
  vars_prompt: 
    - name: pkgtoinstall
      prompt: Which Package to Install? 
      default: telnet
      private: no 
  tasks:
    - name: Install the indicated package
      yum: pkg={{ pkgtoinstall }} state=latest   
