--- # EBS snapshots based on Volume Tags
- hosts: ec2
  connection: local 
  tasks: 
    - name: Finding volumes based on tags of "EBSbackup"
      ec2_vol_facts:
        region: us-east-1
        filters:
            "tag:EBSbackup": True
            attachment.status: attached
      register: ec2
    - name: Taking EC2-snapshots on "tag:EBSbackup" based volumes
      vars:
        volume: "{{item}}"
      ec2_snapshot:
        snapshot_tags:
          Name: "EBS-volume-backup"
          env: "dev"
          expire: "True" 
        region: us-east-1
        volume_id: "{{ volume.id }}"
        description: "Volume-Backup of {{volume.tags.Name}} ({{volume.attachment_set.instance_id}}) taken on {{ ansible_date_time.date }} at {{ansible_date_time.time}} {{ansible_date_time.tz}}"
        last_snapshot_min_age: 60
        state: present
        wait: "no"
      with_items: "{{ec2.volumes}}"
      register: result 
    - name: Deleting snapshots based on "tag:expire" which are older than 5 days
      command: python deloldsnapshots.py
      register: del_snapshots
    - debug: var=del_snapshots
